<!---
<settings>
	<dsn>soundings</dsn>
	<dbtype>mysql</dbtype>
	<fromaddress>soundings@localhost</fromaddress>
	<perpage>4</perpage>
	<tableprefix></tableprefix>
	<version>4.5.3</version>
	<attachmentdir>/Users/ray/Desktop</attachmentdir>
</settings>
--->
